### ISSUE TITLE
hi my friend, where is your code?

### ISSUE THREAD

**Issue by daima2017** [lzxlin/MCLEA#1]
hi my friend, where is your code?

**Comment by lzxlin** [comment]
> hi my friend, where is your code?

Thank you for your attention, the code needs some time to sort out and will be released in the near future.

**Comment by sty945** [comment]
Hello friends, excuse me. Approximately when will the code release?

**Comment by lzxlin** [comment]
> 

Sorry for the delay due to some busy work recently, we plan to release the code at the end of September. Thanks again for your attention.

**Comment by sty945** [comment]
Thank you for your reply.  **I would be very grateful If you can share your code with some running script and detailed instructions for how to use Multi-modal datasets?** I am looking forward to to your excellent work in the future.

**Comment by sty945** [comment]
> > 
> 
> Sorry for the delay due to some busy work recently, we plan to release the code at the end of September. Thanks again for your attention.

Excuse me, Zhenxi, Do you have time to update the code during the National Day holiday?

**Comment by lzxlin** [comment]
> > > 
> > 
> > 
> > Sorry for the delay due to some busy work recently, we plan to release the code at the end of September. Thanks again for your attention.
> 
> Excuse me, Zhenxi, Do you have time to update the code during the National Day holiday?

Sorry for the delay, the code has been uploaded, welcome to reference our work.

**Comment by sty945** [comment]
> > > > 
> > > 
> > > 
> > > Sorry for the delay due to some busy work recently, we plan to release the code at the end of September. Thanks again for your attention.
> > 
> > 
> > Excuse me, Zhenxi, Do you have time to update the code during the National Day holiday?
> 
> Sorry for the delay, the code has been uploaded, welcome to reference our work.

Thank you so much. Hope you are having good holiday.
