### ISSUE TITLE
大佬你这个数据集是不是有问题

### ISSUE THREAD

**Issue by 850587600** [lzxlin/MCLEA#10]
里面的关系id文件好像没有

**Comment by lzxlin** [comment]
>

**Comment by lzxlin** [comment]
> 里面的关系id文件好像没有

每个数据集下的triple_xx的中间id就是关系id

**Comment by 850587600** [comment]
这个我知道，但是这个关系id代表的实体类型是舍弃的是吗

**Comment by lzxlin** [comment]
> 这个我知道，但是这个关系id代表的实体类型是舍弃的是吗

我们没有使用实体类型信息

**Comment by 850587600** [comment]
那大佬我还想问一下，关于结构和关系嵌入你是如何区分嵌入的，结构和关系嵌入我不是太明白你方便讲一下吗

**Comment by lzxlin** [comment]
> 那大佬我还想问一下，关于结构和关系嵌入你是如何区分嵌入的，结构和关系嵌入我不是太明白你方便讲一下吗

结构嵌入就是用GAT编码实体的邻居作为实体的结构表示；关系嵌入就是将实体涉及的所有关系表征为一维向量作为实体的关系表示
