### ISSUE TITLE
关于评价指标的问题

### ISSUE THREAD

**Issue by PrimaLuz** [lzxlin/MCLEA#11]
作者你好，拜读过你的论文后，我对你的研究十分感兴趣。但是我有个疑问，在你的实验设置中采用了Hit@k、MRR指标评估模型性能，这也是实体对齐任务中比较主流的评价指标。但是有部分实体对齐模型采用了Precision、Recall、F1指标来评估模型性能。请问这两种评估体系有什么区别，还有就是两种评价指标是否存在一定的转换关系，比如Hit@1和Precision是否有一定的转换关系。

**Comment by lzxlin** [comment]
> 作者你好，拜读过你的论文后，我对你的研究十分感兴趣。但是我有个疑问，在你的实验设置中采用了Hit@k、MRR指标评估模型性能，这也是实体对齐任务中比较主流的评价指标。但是有部分实体对齐模型采用了Precision、Recall、F1指标来评估模型性能。请问这两种评估体系有什么区别，还有就是两种评价指标是否存在一定的转换关系，比如Hit@1和Precision是否有一定的转换关系。

根据模型的特性可以选择不同的指标，Hit@1和Precision其实是等价的。embedding-based的方法基于相似度给每个entity都有一个对齐结果，所以这些方法的P,R,F1都是一样的，所以embedding-based的方法更多的还是使用Hits@K指标评判。
