### ISSUE TITLE
是否有用到attribute value

### ISSUE THREAD

**Issue by Fitz-like-coding** [lzxlin/MCLEA#12]
作者你好，我最近拜读了您的文章，在attribute embedding这一部分有点疑惑，想了解下做attribute embedding的时候有考虑到attribute的value吗，还是只考虑attribute type就行了？

**Comment by lzxlin** [comment]
> 作者你好，我最近拜读了您的文章，在attribute embedding这一部分有点疑惑，想了解下做attribute embedding的时候有考虑到attribute的value吗，还是只考虑attribute type就行了？

attribute的表示和baseline EVA保持一致，不考虑value
