### ISSUE TITLE
实验在EN-FR-15K等数据集的问题

### ISSUE THREAD

**Issue by haruinia** [lzxlin/MCLEA#13]
我想将ontoea结合多模态特征进行对齐，请问您mclea方法能否在EN-FR-15k，以及不是跨语言知识图谱D-W-15K上应用呢？

**Comment by lzxlin** [comment]
> 我想将ontoea结合多模态特征进行对齐，请问您mclea方法能否在EN-FR-15k，以及不是跨语言知识图谱D-W-15K上应用呢？

可以的
