### ISSUE TITLE
多模态数据集问题

### ISSUE THREAD

**Issue by PrimaLuz** [lzxlin/MCLEA#4]
你您好，根据您的指引，我去https://github.com/mniepert/mmkb/tree/v0.2 了解了这个多模态数据集，但是原始数据集只提供了xxx_EntityTriples.txt、xxx_ImageIndex.txt、xxx_NumericalTriples.txt等，我不清楚如何处理得到您代码中处理好的数据集格式。请可否提供数据预处理的代码，万分感谢！！

**Comment by lzxlin** [comment]
多模态处理后的数据集可以从[百度云盘](https://pan.baidu.com/s/1MLGBNyFjb9LLa4urCk4hCA?_at_=1668166984987#list/path=%2F)下载

**Comment by PrimaLuz** [comment]
> 多模态处理后的数据集可以从[百度云盘](https://pan.baidu.com/s/1MLGBNyFjb9LLa4urCk4hCA?_at_=1668166984987#list/path=%2F)下载

可否提供一下数据集处理的代码，万分感谢

**Comment by Chenfeng1271** [comment]
你好，网盘链接好像失效了

**Comment by lzxlin** [comment]
> 

处理代码已上传，参考[mmkb_convert.py](https://github.com/lzxlin/MCLEA/blob/main/datapro/mmkb_convert.py)

**Comment by lzxlin** [comment]
> 你好，网盘链接好像失效了

我测试可以正常打开，你再试下呢

**Comment by lzxlin** [comment]
> > 多模态处理后的数据集可以从[百度云盘](https://pan.baidu.com/s/1MLGBNyFjb9LLa4urCk4hCA?_at_=1668166984987#list/path=%2F)下载
> 
> 可否提供一下数据集处理的代码，万分感谢

处理代码已上传，参考[mmkb_convert.py](https://github.com/lzxlin/MCLEA/blob/main/datapro/mmkb_convert.py)

**Comment by PrimaLuz** [comment]
> > > 多模态处理后的数据集可以从[百度云盘](https://pan.baidu.com/s/1MLGBNyFjb9LLa4urCk4hCA?_at_=1668166984987#list/path=%2F)下载
> > 
> > 
> > 可否提供一下数据集处理的代码，万分感谢
> 
> 处理代码已上传，参考[mmkb_convert.py](https://github.com/lzxlin/MCLEA/blob/main/datapro/mmkb_convert.py)

十分感谢您的帮助
