### ISSUE TITLE
多模态数据集图片问题

### ISSUE THREAD

**Issue by fmh1art** [lzxlin/MCLEA#5]
作者您好！

根据readme和closed issues，可以找到处理后的图片数据集。但是否可以提供DB15K和FB15K处理前的图片数据呢。您所指引的[repo](https://github.com/mniepert/mmkb)里只提供了FB15K的图片下载urls，请问去哪里可以找到其他两个数据集的图片数据或者下载连接呢？

**Comment by lzxlin** [comment]
我们使用的图片特征来自[MMKB](https://github.com/mniepert/mmkb)提供的VGG16 embedding，没有原始图片数据。原始数据可以参考下论文 https://arxiv.org/abs/1709.02314 ，或者咨询下MMKB作者。

**Comment by fmh1art** [comment]
感谢！祝顺利！
