### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by 850587600** [lzxlin/MCLEA#6]
运行代码的时候总是走到第二轮就内存爆了，想知道是什么原因

**Comment by lzxlin** [comment]
资源不足可以考虑适当减少batch size或者通过梯度累积实现较大的batch size

**Comment by 850587600** [comment]
我把bsize改成1都还是不行，大佬方便给个联系方式吗0.0

**Comment by lzxlin** [comment]
你使用的内存或者显存是多少呢？可以检查下是否是GAT占有资源过多的问题，或者把GAT换成GCN试下

**Comment by 850587600** [comment]
16G运行内存，我是在服务器上跑的我不知道怎么在服务器上看GAT是否占有资源过多

**Comment by lzxlin** [comment]
可以试着调小hidden_units参数，降低GAT的隐层大小，或者把structure_encoder改成"gcn"

**Comment by lzxlin** [comment]
> 可以试着调小hidden_units参数，降低GAT的隐层大小

或者把structure_encoder改成"gcn"

**Comment by 850587600** [comment]
好滴我试下谢谢大佬，不过改成了GCN之后效果是不是就不太好了

**Comment by lzxlin** [comment]
实验效果GAT会比GCN好些，但是GCN速度会更快

**Comment by 850587600** [comment]
大佬我想知道关于属性和关系、实体名嵌入看你的文章好像都是直接送往简单的前馈层，得到嵌入，但是我看其他文章都是利用到了TransE获得关系嵌入和属性特征利用Bert获得嵌入，我想知道您这篇文章为什么这么设计。

**Comment by lzxlin** [comment]
特征的编码器不是本文的核心创新，所以采样了简单MLP层，可以灵活替换不同的编码器至你的项目中
