### ISSUE TITLE
数据问题

### ISSUE THREAD

**Issue by 850587600** [lzxlin/MCLEA#8]
我好像没有看到Kg的属性三元组，好像文件夹只有training_attr_1和training_attr_2，里面也不是常规的属性三元组

**Comment by lzxlin** [comment]
这两个文件每一行只包含每个实体的名字以及包含的所有属性类型，但没有属性值

**Comment by 850587600** [comment]
那文章的属性嵌入单指嵌入属性类型，属性值没有考虑在内吗

**Comment by lzxlin** [comment]
> 那文章的属性嵌入单指嵌入属性类型，属性值没有考虑在内吗

是的
