### ISSUE TITLE
还有一些问题想要请教大佬

### ISSUE THREAD

**Issue by 850587600** [lzxlin/MCLEA#9]
我看大佬的文章说需要改进得地方有增加实体描述信息，如果是增加实体描述得话，这个模态数据从哪里来以及可以怎么转化直接利用知识嵌入简单做向量表示吗？

**Comment by lzxlin** [comment]
可以参考之前使用实体描述信息的一些工作，比如BERT-INT

**Comment by 850587600** [comment]
那就是利用bert获取名字/描述的知识表示，然后与其他特征表示进行拼接吗

**Comment by lzxlin** [comment]
嗯嗯，这是一种直接的方法

**Comment by 850587600** [comment]
我看到大佬代码里面有charembeeding但是好像没有用到吧？

**Comment by lzxlin** [comment]
在DBP15K数据集有用，MMKB数据集没有

**Comment by 850587600** [comment]
那就是把实体对齐分为了两个类型，一个是跨语言的KG利用到了charembeddings，另一种两个不同的KG没有用到是这么理解吗，因为最近想以您这篇为base想创新加个描述模态好像不太够。

**Comment by lzxlin** [comment]
用不用是可选项，为了和前人工作公平比较在MMKB上没有用实体名字信息。加入实体描述直觉上可以丰富长尾实体信息，另外加入本体的OntoEA也是一种思路。

**Comment by 850587600** [comment]
那再您的基础上做创新不能从模态层面考虑而是从模型表示和嵌入融合方面考虑吗

**Comment by lzxlin** [comment]
都可以的

**Comment by 850587600** [comment]
那最终的实体对齐都是通过知识表示形成的矩阵进行的余弦相似度匹配吗
